name: Update backend

on:
  push:
    branches:
      - master

jobs:
  update_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update info
        shell: bash
        run: chmod +x ./.github/scripts/markdown-update-check.sh && ./.github/scripts/markdown-update-check.sh
